- acts like return or break
- destroys FAR of causal function and returns the calling object the exception
- throw can return one of a primitive or derived entity
-
- generally [[anonymous object]] are returned as excpetions